# Generated by Django 3.1.3 on 2023-02-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estrella',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(default='')),
                ('distancia', models.TextField(default='')),
                ('radio', models.FloatField(default='')),
                ('rotacion', models.FloatField(default='')),
                ('edad', models.BigIntegerField(default='')),
                ('ubicacion', models.IntegerField(default='')),
                ('masa', models.IntegerField(default='')),
                ('temperatura', models.FloatField(default='')),
                ('constelacion', models.TextField(default='')),
                ('color', models.TextField(default='')),
            ],
        ),
    ]
