# Generated by Django 3.1.3 on 2023-02-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estrellas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estrella',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estrella',
            name='masa',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estrella',
            name='radio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='estrella',
            name='rotacion',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='estrella',
            name='temperatura',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='estrella',
            name='ubicacion',
            field=models.IntegerField(default=0),
        ),
    ]
